### ISSUE TITLE
Why restrict components to NPM?

### ISSUE THREAD

**Issue by howardroark** [bionode/bionode#14]
Close this up if you feel like I am trolling (which I am) :) No offence taken and I apologize!  Just thought that given the cutting edge nature of bioinformatics, you may want to help think of ways to push the boundaries of how we use Node.js :)

There is not an easy alternative to NPM as of yet, but the idea is the main point.  Why not just source a package from where ever you please?  Instead of a "node_modules" folder at the root, offer a "modules" folder instead.  NPM ends up limiting the names people can use and could be described as a cumbersome process. Just about every NPM package is a GitHub repo anyway, why not cut out the middle man.

It would be amazing if there was a simple schema that allowed you to source packages from Git over ssh, http servers and local file systems.  To follow the UNIX philosophy well there is likely a few separate projects would have to spin out of the idea.  I just feel that eventually NPM has to go, or any body which claims an amount authority as to what stays and goes.

For inspiration there are these projects...

https://github.com/duojs/duo (this is really focused on the browser, but the core idea is key)
https://github.com/ismotgroup/bring (the concept of replacing "require" with an alternative is really the point here)

Thanks!

**Comment by bmpvieira** [comment]
Thanks @howardroark and @greenify for this interesting discussion. Nowadays NPM has [more modules than any other package manager](http://modulecounts.com) and most importantly "It Just Works™". Although in JavaScript there is some [other interesting package managers](https://github.com/showcases/package-managers?s=language), I think this is a subject where "less is more", and NPM works [fine on the frontend too](http://beletsky.net/2015/04/npm-for-everything.html).

@howardroark also check [this answer on another thread](https://github.com/bionode/bionode/issues/9#issuecomment-49566087), in particular the part where he mentions how a game project got screwed because the Go language package manager fetches directly from version control systems and thus doesn't host a copy of the dependency, which makes it vulnerable to changes. That is why we shouldn't just rely on Git/GitHub.

I'm going to close this, but feel free to continue to discuss on [gitter.im/bionode/bionode](http://gitter.im/bionode/bionode) or IRC [#bionode](http://irccloud.com/#!/ircs://irc.freenode.net:6697/%23bionode)
