### ISSUE TITLE
windows install

### ISSUE THREAD

**Issue by syzer** [bionode/bionode#20]
```
npm ERR! Windows_NT 6.1.7601
npm ERR! node v0.10.26
npm ERR! npm  v2.1.14
npm ERR! code ELIFECYCLE

npm ERR! bionode-sam@1.0.1 preinstall: `sam/build.sh`
npm ERR! Exit status 1
```
the binode installer should mention that you need to compile samtools BEFORE installing binode

**Comment by bmpvieira** [comment]
Bionode should compile automatically samtools so you don't need to. `bionode-sam` is using a shell script ([build.sh](https://github.com/bionode/bionode-sam/blob/master/sam/build.sh)) so that's why it's not working on Windows. However, even in Linux/OSX, this is still currently prone to fail (see bionode/bionode#29) so we are considering alternatives for wrapper modules that require binaries. The other modules (e.g., bionode-ncbi) should work.
I'm closing this, please feel free to discuss it further on bionode/bionode#29.
